param(
    [switch]$Apply,
    [switch]$Json,
    [int]$Iterations = 1
)

$ErrorActionPreference = "Stop"

$ProjectRoot = Resolve-Path (Join-Path $PSScriptRoot "..")
$Roadmap = Join-Path $ProjectRoot "docs\ROADMAP.md"

function Invoke-JsonCommand {
    param([string[]]$Command)
    $Output = & $Command[0] $Command[1..($Command.Count - 1)]
    return $Output | ConvertFrom-Json
}

$Quick = Invoke-JsonCommand @("powershell", "-NoProfile", "-ExecutionPolicy", "Bypass", "-File", (Join-Path $PSScriptRoot "ana_quick_check.ps1"), "-Iterations", [string]$Iterations, "-Json")
$Maintenance = Invoke-JsonCommand @("powershell", "-NoProfile", "-ExecutionPolicy", "Bypass", "-File", (Join-Path $PSScriptRoot "ana_maintenance.ps1"), "-Json")
$ScanRoots = @(
    (Join-Path $ProjectRoot "scripts"),
    (Join-Path $ProjectRoot "tests"),
    (Join-Path $ProjectRoot "cascade_integration")
)
$ScanFiles = Get-ChildItem -LiteralPath $ScanRoots -Recurse -File -Include "*.ps1", "*.py" -ErrorAction SilentlyContinue |
    Where-Object { $_.FullName -notmatch "\\__pycache__\\" }
$TodoHits = @()
$RiskHits = @()
$BroadExceptHits = @()
foreach ($File in $ScanFiles) {
    $Lines = Get-Content -LiteralPath $File.FullName -ErrorAction SilentlyContinue
    for ($Index = 0; $Index -lt $Lines.Count; $Index++) {
        $Line = $Lines[$Index]
        $Relative = Resolve-Path -LiteralPath $File.FullName -Relative
        if ($Line -match "TODO|FIXME") {
            $TodoHits += "${Relative}:$($Index + 1)"
        }
        $WindowStart = [math]::Max(0, $Index - 5)
        $Nearby = ($Lines[$WindowStart..$Index] -join "`n")
        $GuardedMutation = $Nearby -match '\$Apply'
        $PlannerPatternLine = $Relative -like "*ana_planner.ps1" -and ($Line.Contains('$Line -match') -or $Line.Contains('Add-Task'))
        if ($Line -match "Remove-Item|Start-Process|Invoke-Expression|\biex\b" -and -not $GuardedMutation -and -not $PlannerPatternLine) {
            $RiskHits += "${Relative}:$($Index + 1)"
        }
        if ($Line -match "except Exception") {
            $BroadExceptHits += "${Relative}:$($Index + 1)"
        }
    }
}

$Tasks = @()

function Add-Task {
    param(
        [string]$Id,
        [string]$Title,
        [int]$Impact,
        [int]$Risk,
        [int]$Cost,
        [string]$Evidence,
        [string]$Action
    )
    $Score = [math]::Round(($Impact * 2 + $Risk) - $Cost, 2)
    $script:Tasks += [ordered]@{
        id = $Id
        title = $Title
        score = $Score
        impact = $Impact
        risk = $Risk
        cost = $Cost
        evidence = $Evidence
        action = $Action
    }
}

if ($Maintenance.log_archive.compress_candidates -gt 0) {
    Add-Task "archive-compression" "Compress log archives" 8 3 2 "$($Maintenance.log_archive.compress_candidates) uncompressed archive directories" "Run .\scripts\ana_maintenance.ps1 -CompressArchive -Apply"
}
if ($Maintenance.items[0].over_limit) {
    Add-Task "active-log-size" "Reduce active log footprint" 8 4 3 "ANA logs $($Maintenance.items[0].size_mb) MB over $($Maintenance.items[0].max_mb) MB" "Run maintenance rotation dry-run, then apply if safe"
}
if ($Quick.benchmark.agent_coach.avg_ms -gt 120) {
    Add-Task "agent-coach-latency" "Profile agent_coach latency" 6 2 3 "agent_coach avg $($Quick.benchmark.agent_coach.avg_ms) ms" "Profile direct tool loading and memory reads"
}
if ($Quick.smoke.failed -gt 0) {
    Add-Task "smoke-regression" "Fix smoke test failures" 10 8 4 "$($Quick.smoke.failed) smoke failures" "Inspect failed smoke result before mutations"
}
if ($RiskHits.Count -gt 0) {
    Add-Task "script-risk-review" "Review risky script operations" 7 5 3 "$($RiskHits.Count) risky operation references" "Inspect Remove-Item/Start-Process usage and ensure explicit apply/dry-run guards"
}
if ($BroadExceptHits.Count -gt 5) {
    Add-Task "exception-specificity" "Tighten broad exception handling" 5 2 4 "$($BroadExceptHits.Count) broad exception handlers" "Prioritize direct_bridge/cascade_bridge handlers that hide actionable errors"
}
if ($TodoHits.Count -gt 0) {
    Add-Task "todo-cleanup" "Resolve TODO/FIXME markers" 3 1 2 "$($TodoHits.Count) TODO/FIXME markers" "Patch or document each marker"
}

if ($Tasks.Count -eq 0) {
    Add-Task "steady-state" "Maintain green daily loop" 4 1 1 "quick check and maintenance are green" "Continue daily checks and document drift"
}

$SortedTasks = @($Tasks | Sort-Object { $_.score } -Descending)
$Timestamp = Get-Date -Format "yyyy-MM-dd HH:mm:ss"

$RoadmapText = @"
# Roadmap

Generated by `scripts/ana_planner.ps1` at $Timestamp.

## Auto Priorities

"@

foreach ($Task in $SortedTasks) {
    $RoadmapText += "- [$($Task.id)] score=$($Task.score) impact=$($Task.impact) risk=$($Task.risk) cost=$($Task.cost): $($Task.title)`n"
    $RoadmapText += "  - Evidence: $($Task.evidence)`n"
    $RoadmapText += "  - Action: $($Task.action)`n"
}

$RoadmapText += @"

## Guardrails

- Direct execution only by default.
- Apply maintenance mutations only with explicit flags.
- Verify with `scripts/ana_quick_check.ps1` after changes.
"@

if ($Apply) {
    Set-Content -LiteralPath $Roadmap -Value $RoadmapText -Encoding UTF8
}

$Result = [ordered]@{
    success = $true
    apply = [bool]$Apply
    timestamp = $Timestamp
    task_count = $SortedTasks.Count
    tasks = $SortedTasks
    debt_scan = @{
        files = $ScanFiles.Count
        todo_hits = $TodoHits.Count
        risky_operation_hits = $RiskHits.Count
        broad_exception_hits = $BroadExceptHits.Count
        risky_operation_examples = @($RiskHits | Select-Object -First 5)
        broad_exception_examples = @($BroadExceptHits | Select-Object -First 5)
    }
    roadmap = [string]$Roadmap
    next_action = if ($Apply) { "Roadmap updated. Execute top task if it is safe." } else { "Dry-run planner complete. Use -Apply to update ROADMAP.md." }
}

if ($Json) {
    $Result | ConvertTo-Json -Depth 8
}
else {
    Write-Host "PASS ANA planner"
    Write-Host "Tasks: $($SortedTasks.Count)"
    Write-Host "Top: $($SortedTasks[0].id) - $($SortedTasks[0].title)"
    Write-Host "Next: $($Result.next_action)"
}
